// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateChannel(arg1, arg2) {
  return window['go']['main']['App']['CreateChannel'](arg1, arg2);
}

export function DeleteChannel(arg1) {
  return window['go']['main']['App']['DeleteChannel'](arg1);
}

export function GetChannels() {
  return window['go']['main']['App']['GetChannels']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDiscoveredPeers() {
  return window['go']['main']['App']['GetDiscoveredPeers']();
}

export function GetSignalingURL() {
  return window['go']['main']['App']['GetSignalingURL']();
}

export function RenameChannel(arg1, arg2) {
  return window['go']['main']['App']['RenameChannel'](arg1, arg2);
}

export function Shutdown() {
  return window['go']['main']['App']['Shutdown']();
}
