// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {channel} from '../models';
import {config} from '../models';

export function CreateChannel(arg1:string,arg2:string):Promise<void>;

export function DeleteChannel(arg1:string):Promise<void>;

export function GetChannels():Promise<Array<channel.ChannelInfo>>;

export function GetConfig():Promise<config.Config>;

export function GetDiscoveredPeers():Promise<Array<main.Peer>>;

export function GetSignalingURL():Promise<string>;

export function RenameChannel(arg1:string,arg2:string):Promise<void>;

export function Shutdown():Promise<void>;
